source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

pod 'DateTools'
pod 'Alamofire', '~> 3.0.1'
pod 'AlamofireImage', '~> 2.0'
pod 'SnapKit', '~> 0.15.0'
pod 'Realm'
pod 'RealmSwift'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'CTAssetsPickerController',  '~> 3.1.0'
pod 'OAStackView'
pod 'DeviceUtil'
pod 'Google-Mobile-Ads-SDK'
pod 'ReactKit'
pod 'NibDesignable'
pod 'SwiftyColor'
pod 'IQKeyboardManagerSwift'