fastlane_version "1.63.0"

default_platform :ios

def increment_version_build_numbers
  increment_build_number
  prompt_text = "What's the next version number? (ex: x.x.x)"
  version_number  = prompt(text: prompt_text)
  increment_version_number(version_number: version_number)
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # ensure_git_status_clean
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Swish")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    increment_version_build_numbers
    cert(output_path: "fastlane/output")
    sigh(
      app_identifier: "com.yooiistudios.swish",
      force: true,
      output_path: "fastlane/output"
    )
    commit_version_bump(
      message: "Version bump by fastlane",
      force: true
    )
    gym(
      scheme: "Swish",
      clean: true,
      output_directory: "fastlane/output"
    ) # Build your app
    pilot(wait_processing_interval: 60) # Interval in seconds to wait for iTunes Connect
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Swish") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
