fastlane_version "1.63.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # ensure_git_status_clean
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Swish")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Swish") # Build your app - more options available
    pilot
  end

  lane :v do
    project_file = 'Swish.xcodeproj'
    # increment_build_number(xcodeproj: project_file) # version bump
    # increment_build_number
    prompt_text = "What's the next version number? (ex: x.x.x)"
    version_number  = prompt(text: prompt_text)
#    increment_version_number(version_number: version_number)
    commit_version_bump(
      message: "Version bump by fastlane",
      xcodeproj: project_file
    )

  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Swish") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
